### ISSUE TITLE
App팀 코드 리뷰

### ISSUE THREAD

**Issue by LeeBumSeok** [kookmin-sw/capstone-2022-07#13]
1. mainScreen.dart
    1. 일단 코스피만 진행할거기 때문에 코스닥은 Feature로 남겨두고 코스닥 부분 삭제했습니다.
    2. mediaquery.size를 위젯마다 선언하는 것 보다 size 변수를 파라미터로 주는 것이 좋습니다.
    3. 해당 페이지에서만 사용할 위젯이면 클래스 안에 Widget을 선언하는 것이 좋습니다.
    4. Widget tempStatusbar() 삭제
        1. Widget Navigationbar()를 AppBar로 대체하면서 필요 없어진 위젯
    5. Widget Navigationbar() 삭제
        1. Scaffold에 appbar 항목이 있기 때문에 필요하지 않음
    6. Widget Stockindex()
        1. Boxdecoration 부분 Component로 따로 뺌: 계속 사용할 내용은 컴포넌트로 뺴는게 좋음
        2. 코스닥 부분 삭제
        3. 불필요하게 겹쳐 있는 Row, Column, Container, Expanded 삭제
    7. Widget Build()
        1. MaterialApp 삭제: 실행하는 홈 화면이 아니기 때문에 불필요합니다.
        2. Builder 제거
        3. Appbar 추가: 컴포넌트로 빼놓음 (main_app_bar.dart, mainAppBar(context))
        4. 불필요한 위젯들 제거
2. interestScreen.dart
    1. Widget tempStatusbar() 삭제
        1. Widget Navigationbar()를 AppBar로 대체하면서 필요 없어진 위젯
    2. Widget Navigationbar() 삭제
        1. Scaffold에 appbar 항목이 있기 때문에 필요하지 않음
    3. Widget Stockcard()
        1. 자세히 container 버튼으로 바꿈
        2. 이미지들 경로 맞춤

**Comment by Leegeonmin** [comment]
완료
