### ISSUE TITLE
Stockscreen 종목 정보에 맞는 위젯 

### ISSUE THREAD

**Issue by Leegeonmin** [kookmin-sw/capstone-2022-07#17]
종목 정보, 종목 뉴스 버튼 클릭 시
아래로 list가 펼쳐지게 하는 위젯을 못 찾는 중입니다.

**Comment by LeeBumSeok** [comment]
https://ichi.pro/ko/flutterui-jeobneun-sel-244220270558928

이거 이용하면 될 것 같아요!

**Comment by Leegeonmin** [comment]
사용법이 너무 복잡해서
https://api.flutter.dev/flutter/material/ExpansionTile-class.html 
Expansiontile 쓰기러했습니다
